name: Python Pipeline

on: [push]

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/chekout@v2
      - run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/chekout@v2
    - uses: actions/upload-pages-artifact@v1.0.4
      with: 
        name: hello
        path: .
   
